services:
    app:
        build: .
        container_name: laravel-octane-app
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
            OCTANE_WORKERS: 8
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
